apiVersion: v1
kind: Template
labels:
  app: ahjenkinsbase
  template: jenkinshrfinora-template
message: This Template is for creating the Jenkins Latest base image
metadata:
  annotations:
    description: |-
      Jenkins Base Image

      NOTE: You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-jenkins
    openshift.io/display-name: Jenkins Base Image
    openshift.io/documentation-url: https://docs.openshift.org/latest/using_images/other_images/jenkins.html
    openshift.io/long-description: This template deploys a Jenkins server capable
      of managing OpenShift Pipeline builds and supporting OpenShift-based oauth login for HR Finance Oracle.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
    tags: instant-app,jenkins,ahjenkinsbase
  creationTimestamp: null
  name: ahjenkinsbase
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ahjenkinsbase
    name: ahjenkinsbase
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ahjenkinsbase:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: "Git"
      git:
        uri: "ssh://git@bitbucket-lan.ah.nl:7999/aut/ah-openshift-jenkins-base.git"
      contextDir: ""
      sourceSecret:
        name: "bitbucketssh"      
    strategy:
      type: Docker
      dockerStrategy:
        noCache: false
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
      
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ahjenkinsbase
    name: ahjenkinsbase
  spec:
    lookupPolicy:
      local: false
